spring.application.name=valemorar
spring.datasource.url=jdbc:postgresql://localhost:5439/valemorar_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Cria/Atualiza o esquema no banco automaticamente ao iniciar a aplicação
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
